### ISSUE TITLE
Cant get nested Workflows to work?

### ISSUE THREAD

**Issue by viezel** [ksassnowski/venture#17] opened 2021-01-13 14:15 UTC
I wanted to test out the nested workflows, so I did the following. 
Its a typical scenario of document signing.

I have a bunch of dummy jobs that does nothing else than write a line in the log. just to see that it works. 

```php
return Workflow::define('Sign a document')
    ->addJob(new PrepareDocumentForSigning($this->document))
    ->addWorkflow(new FirstOrderSigning($this->document), [
        PrepareDocumentForSigning::class,
    ])
    ->addWorkflow(new SecondOrderSigning($this->document), [
        FirstOrderSigning::class,
    ])
    ->addJob(new ExecuteDocument($this->document), [
        SecondOrderSigning::class,
    ])
    ->addJob(new SendExecutedDocument($this->document), [
        ExecuteDocument::class,
    ])
    ->catch(function (\Sassnowski\Venture\Models\Workflow $workflow, $job, Throwable $e) {
        info("Workflow cancelled " .  $e);
        $workflow->cancel();
    });
```

`FirstOrderSigning` and `SecondOrderSigning` are identical and its content is: 

```php
class FirstOrderSigning extends AbstractWorkflow
{
    private Document $document;

    public function __construct(Document $document)
    {
        $this->document = $document;
    }

    public function definition(): WorkflowDefinition
    {
        return Workflow::define('Sign a document')
            ->addJob(new SendSigningEmailInvite($this->document))
            ->addJob(new CaptureSignature($this->document), [
                SendSigningEmailInvite::class,
            ]);
    }
}
```

I run 

```php
SignDocumentWorkflow::start($document);
```

but Horizon outputs only 1 job executed: (the one before the nested workflow)

![image](https://user-images.githubusercontent.com/312065/104462939-737bd600-55b1-11eb-9545-fafddd60aa8b.png)

However, if I remove those workflows and only use addJobs - then add 3 jobs get executed. 

```php
return Workflow::define('Sign a document')
    ->addJob(new PrepareDocumentForSigning($this->document))
    ->addJob(new ExecuteDocument($this->document), [
        PrepareDocumentForSigning::class,
    ])
    ->addJob(new SendExecutedDocument($this->document), [
        ExecuteDocument::class,
    ])
    ->catch(function (\Sassnowski\Venture\Models\Workflow $workflow, $job, Throwable $e) {
        info("Workflow cancelled " .  $e);
        $workflow->cancel();
    });
```

![image](https://user-images.githubusercontent.com/312065/104463175-ba69cb80-55b1-11eb-98f3-bf6e5c1764c9.png)

What am I missing here?

**Comment by ksassnowski** [comment] 2021-01-13 14:48
Hm, that's definitely strange, your configuration looks correct. I'll have to try and reproduce this locally.

**Comment by ksassnowski** [comment] 2021-01-13 15:54
I'm unable to reproduce this issue locally. I have a hunch about what could be going on, however. Do `FirstOrderSigning` and `SecondOrderJoining` have the same jobs, or at least some shared jobs? Can you try and _only_ add the `FirstOrderSigning` Workflow and see if it works this way?

**Comment by viezel** [comment] 2021-01-14 11:58
yes they do.

```php
class FirstOrderSigning extends AbstractWorkflow
{
    private Document $document;

    public function __construct(Document $document)
    {
        $this->document = $document;
    }

    public function definition(): WorkflowDefinition
    {
        return Workflow::define('Sign a document')
            ->addJob(new SendSigningEmailInvite($this->document))
            ->addJob(new CaptureSignature($this->document), [
                SendSigningEmailInvite::class,
            ]);
    }
}
```

```php
class SecondOrderSigning extends AbstractWorkflow
{
    private Document $document;

    public function __construct(Document $document)
    {
        $this->document = $document;
    }

    public function definition(): WorkflowDefinition
    {
        return Workflow::define('Sign a document')
            ->addJob(new SendSigningEmailInvite($this->document))
            ->addJob(new CaptureSignature($this->document), [
                SendSigningEmailInvite::class,
            ]);
    }
}
```

**Comment by viezel** [comment] 2021-01-14 12:03
Ok, this is the case. If I do not use `SecondOrderSigning ` in the workflow, then everything works. 

But this means we cannot use jobs in different scenarios. Im super interested in getting https://github.com/ksassnowski/venture/pull/14 merged in now :D Otherwise it will be super hard to build up more complex scenarios. 

Secondly, maybe it could be improved that it does not fail silently. There were no exceptions or any indication what was not working as excepted.

**Comment by ksassnowski** [comment] 2021-02-28 15:29
Can you check out the `3.0.0-RC1` tag and tell me if it solves your problem? You will probably have to change your code slightly. I tried to document the changes in the release description on Github. Thanks!

**Comment by viezel** [comment] 2021-03-01 10:37
@ksassnowski it works well.

**Comment by viezel** [comment] 2021-03-01 10:52
Interesting.. The below also works. So I can add the same nested workflow (FirstOrderSigning) multiple times and give each an unique identifier. 

```php
Workflow::define('Sign a document Workflow')
    ->addJob(new PrepareDocumentForSigning($this->document))
    ->addWorkflow(new FirstOrderSigning($this->document), [
        PrepareDocumentForSigning::class,
    ], "batch1")
    ->addWorkflow(new FirstOrderSigning($this->document), [
        "batch1", 
    ], "batch2")
    ->addJob(new ExecuteDocument($this->document), [
        "batch2",
    ])
    ->addJob(new SendExecutedDocument($this->document), [
        ExecuteDocument::class,
    ]);
```

But how unique is this identifier? If I run it many times, which each WorkflowDefinition knows which "batch1" belongs to which?

**Comment by ksassnowski** [comment] 2021-03-01 10:58
Not sure if I understand your question. The id just needs to be unique within the definition of the Workflow. It doesn't matter how many times you then start the workflow. So let's say your code lives in a class like this.

```php
class DocumentSigningWorkflow extends AbstractWorkflow
{
    public function definition(): WorkflowDefinition
    {
        return Workflow::define('Sign a document Workflow')
            ->addJob(new PrepareDocumentForSigning($this->document))
            ->addWorkflow(new FirstOrderSigning($this->document), [
                PrepareDocumentForSigning::class,
            ], "batch1")
            ->addWorkflow(new FirstOrderSigning($this->document), [
                "batch1", 
            ], "batch2")
            ->addJob(new ExecuteDocument($this->document), [
                "batch2",
            ])
            ->addJob(new SendExecutedDocument($this->document), [
                ExecuteDocument::class,
            ]);
    }
}
```

This would work fine and you can start as many `DocumentSigningWorkflows` as you want. The ids don't leak outside the workflow instance.

Does this answer your question?

**Comment by viezel** [comment] 2021-03-01 10:59
it does. thats great.

**Comment by ksassnowski** [comment] 2021-03-01 11:04
Great. I'll leave this issue open until I've tagged a stable version 3.

**Comment by ksassnowski** [comment] 2021-03-30 05:59
Version 3 just got released so I'm going to close this issue.

**Closed by ksassnowski** 2021-03-30 05:59 UTC
Labels: bug
